export type AdminLanguage = "en" | "zh";
export type AdminTheme = "dark" | "light";

export const ADMIN_LANGUAGE_COOKIE = "finhalo_admin_lang";
export const ADMIN_THEME_COOKIE = "finhalo_admin_theme";

export const adminTranslations = {
  en: {
    common: {
      nav: {
        dashboard: "Dashboard",
        users: "Users",
        accounts: "Trading Accounts",
        brokers: "Brokers",
        campaigns: "Campaigns",
        campaign: "Campaigns",
        commission: "Commission",
        finance: "Finance",
        network: "Network",
        referral: "Referral",
        promotions: "Referral",
        support: "Support",
        settings: "Settings",
      },
      shell: {
        globalSearchLabel: "Global search",
        searchPlaceholder: "Search users, accounts, batches, or withdrawals...",
        alerts: "Alerts",
        admin: "Admin",
        environment: "Environment",
        previewMode: "Preview Mode",
        english: "EN",
        chinese: "中文",
        light: "Light",
        dark: "Dark",
      },
      actions: {
        clear: "Clear",
        viewUser: "View User",
        viewAccount: "View Account",
        viewCommission: "View Commission",
        viewFinance: "View Finance",
        viewCoverage: "View Coverage",
        viewNetworkSnapshot: "View Network Snapshot",
        batchApprove: "Batch Approve",
        batchReject: "Batch Reject",
        updatePlaceholder: "Update Placeholder",
        postAdjustment: "Post Adjustment",
      },
      labels: {
        search: "Search",
        overview: "Overview",
        contextRelationship: "Context / Relationship",
        relatedActivityReferences: "Related Activity / References",
        handoff: "Handoff",
        accountId: "Account ID",
        broker: "Broker",
        status: "Status",
        createdAt: "Created At",
        updatedAt: "Updated At",
        validation: "Validation",
        category: "Category",
        current: "Current",
        historical: "Historical",
        currentSnapshot: "Current Snapshot",
        historicalSnapshot: "Historical Snapshot",
        relationshipSnapshotId: "Relationship Snapshot ID",
        snapshotId: "Snapshot ID",
        snapshotCode: "Snapshot Code",
        snapshotStatus: "Snapshot Status",
        effectiveFrom: "Effective From",
        effectiveTo: "Effective To",
        relationshipDepth: "Relationship Depth",
        timelinePreview: "Timeline Preview",
      },
      filters: {
        allStatuses: "All statuses",
        allCategories: "All categories",
        allBrokers: "All brokers",
      },
      empty: {
        dash: "—",
      },
    },
    account: {
      title: "Trading Accounts",
      description:
        "Account-level operating hub for ownership, broker context, and IB relationship snapshots across downstream commission and finance workflows.",
      totalAccounts: "Total Accounts",
      activeAccounts: "Active Accounts",
      accountsWithL2: "Accounts With L2",
      brokersCovered: "Brokers Covered",
      directoryTitle: "Trading Account Directory",
      directoryDescription:
        "Search all trading accounts across brokers and review account identity first, then ownership and account-bound L1/L2 relationships without collapsing them into a user-level hierarchy.",
      overviewDescription:
        "Trading Accounts is the primary surface for account-level relationship and audit context.",
      relationshipDescription:
        "This snapshot is bound to the trading account. Downstream commission, rebate, and finance records follow the relationship snapshot captured at generation time.",
      historyDescription:
        "Relationship updates apply only to future records. Historical versions remain unchanged.",
      historyHighlightedSuffix: "The matching deep-linked snapshot is highlighted below.",
      activityDescription:
        "Use this account as the operating anchor for downstream commission explanation, rebate records, finance entries, and withdrawal operations.",
      handoffDescription:
        "Use the account as the central operational hub, with a clear return path to the owner and forward paths into downstream commission and finance modules.",
      owner: "User / Owner",
      userId: "User ID",
      accountType: "Account Type",
      traderUserIdOnAccount: "Trader User ID on Account",
      relationshipSnapshot: "Relationship Snapshot",
      snapshotHistory: "Snapshot History",
      relatedActivity: "Related Activity",
      relationshipRoles: "Relationship Roles",
      trader: "Trader",
      l1Ib: "L1 IB",
      l2Ib: "L2 IB",
      active: "Active",
      monitoring: "Monitoring",
      suspended: "Suspended",
      traderOnly: "Trader Only",
      hasL1: "Has L1",
      hasL2: "Has L2",
      traderAccountSearchPlaceholder: "Search accounts by ID, owner, trader, snapshot, or IB",
      noAccounts: "No trading accounts match the current search and filters.",
      commissionCount: "Commission",
      rebateCount: "Rebate",
      financeCount: "Finance",
      withdrawalCount: "Withdrawals",
    },
    network: {
      title: "Network",
      description:
        "Explore IB-centric coverage across direct accounts, L1 IB rollups, and the current account-level relationship footprint.",
      explorerTitle: "IB Coverage Explorer",
      explorerDescription:
        "Network focuses on IB coverage visibility and the current account-level relationship footprint. Historical relationship inspection belongs to Trading Accounts.",
      helper:
        "This view shows current account-level IB coverage only. Historical relationship inspection belongs to Trading Accounts.",
      searchIb: "Search IB",
      searchPlaceholder: "Search IB user ID or name",
      ibSelection: "IB Selection",
      selectedIb: "Selected IB",
      currentIb: "Current IB",
      previousIb: "Previous IB",
      backToPreviousIb: "Back to Previous IB",
      noIbSelected: "No IB selected",
      unknownIb: "Unknown IB",
      directClientAccounts: "Covered Accounts (Direct)",
      coveredL1Ibs: "Covered L1 IBs",
      totalCoveredAccounts: "Total Covered Accounts",
      activeCoveredAccounts: "Active Covered Accounts",
      upstreamL2Context: "Upstream L2 Context",
      upstreamL2Description:
        "Distinct upstream L2 IBs currently linked to the selected IB when it appears as L1 on covered accounts.",
      upstreamL2Empty:
        "No upstream L2 context is associated with the selected IB in the current coverage data.",
      directClientsDescription:
        "Accounts currently covered directly by the selected IB as L1. Row click opens the related account and snapshot context.",
      l1UnderL2Title: "L1 IBs Under This L2",
      l1UnderL2Description:
        "L1 IBs whose covered accounts currently roll up under the selected IB as L2. Row click pivots the explorer into that L1 coverage view.",
      noDirectClients: "No direct client accounts found for the selected IB.",
      noCoveredL1s: "No L1 IB coverage found for the selected IB.",
      noCoverage: "No IB relationship coverage is available in the current mock dataset.",
      directClientAccountLabel: "Direct Client Accounts",
      coveredAccounts: "Covered Accounts",
      activeAccounts: "Active Accounts",
      snapshotStatus: "Snapshot Status",
    },
    finance: {
      title: "Finance",
      description:
        "Downstream finance workspace for recorded entries, withdrawal approvals, adjustments, and reconciliation review.",
      modulesTitle: "Finance Modules",
      modulesDescription:
        "Use Finance to review recorded entries, approve operational withdrawals, manage adjustments, and reconcile totals against commission outputs.",
      totalLedgerAmount: "Total Ledger Amount",
      pendingWithdrawals: "Pending Withdrawals",
      adjustmentsThisMonth: "Adjustments This Month",
      reconciliationAlerts: "Reconciliation Alerts",
      withdrawals: "Withdrawals",
      ledger: "Ledger",
      adjustments: "Adjustments",
      reconciliation: "Reconciliation",
      ledgerTitle: "Ledger",
      ledgerDescription:
        "Immutable finance records for audit review, downstream rebate references, and recorded operations.",
      ledgerPanelTitle: "Ledger Records",
      ledgerPanelDescription:
        "Finance ledger entries are immutable records once written and serve as the downstream record layer for commission outputs.",
      ledgerFooter: "Immutable record view for audit and reconciliation only.",
      postedEntries: "Posted Entries",
      pendingEntries: "Pending Entries",
      reversedEntries: "Reversed Entries",
      withdrawalsTitle: "Withdrawals",
      withdrawalsDescription:
        "Withdrawal approval list and operational placeholders for request review.",
      withdrawalPanelTitle: "Withdrawal Approval List",
      withdrawalPanelDescription:
        "Pending, approved, and rejected describe operational review state for withdrawal requests.",
      withdrawalPanelNote:
        "Approval controls are placeholder workflow actions and do not post real finance updates in this mock flow.",
      approvalVolume: "Approval Volume",
      gasFees: "Gas Fees",
      rejected: "Rejected",
      gasFeeConfiguration: "Gas Fee Configuration",
      defaultFee: "Default",
      networkLabel: "Network",
      updatedLabel: "Updated",
      placeholderOnly: "Placeholder only. This control does not submit live finance changes yet.",
      modules: {
        withdrawals: "Review withdrawal requests, batch actions, and gas fee placeholders.",
        ledger: "Inspect immutable finance records and rebate-linked entries.",
        adjustments: "Review manual balance adjustments and operator notes.",
        reconciliation: "Compare commission inputs, ledger totals, and payout differences.",
      },
    },
    commission: {
      title: "Commission Center",
      description:
        "Review broker commission inputs, validate breakdown outputs, simulate outcomes, and hand off finalized records into Finance.",
      uploadCommission: "Upload Commission",
      uploadTitle: "Commission Upload",
      uploadDescription:
        "Start a new broker commission import. File mapping and validation will run before any batch is created.",
      uploadPlaceholderTitle: "Upload Area",
      uploadPlaceholderDescription:
        "File drop, field mapping, and validation controls will be connected here in the next workflow pass.",
      supportedFormats: "Supported formats: CSV, XLSX",
      mappingValidationNote:
        "Column mapping and validation will be completed before import is confirmed.",
      batchManagement: "Batch Management",
      simulation: "Simulation",
      clear: "Clear",
      brokerInputs: "Broker Inputs",
      commissionBreakdown: "Commission Breakdown",
      rebateRecords: "Rebate Records",
      filteredByAccount: "Filtered by Account",
      panelDescriptions: {
        inputs: "Review imported broker inputs before validation and downstream breakdown.",
        allocation:
          "Inspect commission split outputs and use the drawer for waterfall detail, relationship context, and finance handoff.",
        rebates: "Review finalized rebate entries generated from the commission breakdown pipeline.",
      },
      searchPlaceholder: "Search commission / batch / broker / account",
      summary: {
        totalCommission: "Total Commission",
        imported: "Imported",
        validated: "Validated",
        processed: "Processed",
        totalGross: "Total Gross",
        totalRebate: "Total Rebate",
        totalPlatformShare: "Total Platform Share",
        records: "Records",
        totalPaid: "Total Paid",
        pending: "Pending",
        settled: "Settled",
      },
      helper: {
        inputStages:
          "Imported, validated, and processed indicate upstream commission pipeline stages before downstream breakdown.",
        allocationStages:
          "Imported, validated, and processed indicate commission pipeline stages before downstream finance records.",
        rebatePipeline: "Represents finalized rebate entries derived from commission breakdown.",
        rebateStates:
          "Pending, posted, and reversed indicate rebate record state before or after finance recording.",
        relationshipNote:
          "This commission breakdown follows the account-level relationship snapshot captured at generation time.",
      },
    },
    support: {
      title: "Support",
      description:
        "Operational support queue for ticket review, requester context, and clean handoff into linked users, trading accounts, commission, and finance records.",
      totalTickets: "Total Tickets",
      openTickets: "Open Tickets",
      inProgress: "In Progress",
      resolved: "Resolved",
      queueTitle: "Support Queue",
      queueDescription:
        "Review support workload, inspect requester and account context, and move into the linked operational modules when a specific user or trading account is involved.",
      searchPlaceholder: "Search tickets by ID, subject, requester, or account",
      noAccount: "No Account",
      noTickets: "No support tickets match the current search and filters.",
      subject: "Subject",
      priority: "Priority",
      requester: "User / Requester",
      relatedModule: "Related Module",
      ticketId: "Ticket ID",
      overviewTitle: "Overview",
      requesterLabel: "Requester",
      email: "Email",
      relatedContextTitle: "Related Activity / References",
      withdrawalId: "Withdrawal ID",
      commissionId: "Commission ID",
      rebateRecordId: "Rebate Record ID",
      ledgerRef: "Ledger Ref",
      updatedAtNote: "Latest activity recorded at",
      statusOptions: {
        open: "Open",
        in_progress: "In Progress",
        waiting_user: "Waiting User",
        resolved: "Resolved",
        closed: "Closed",
      },
      categoryOptions: {
        account: "Account",
        commission: "Commission",
        rebate: "Rebate",
        withdrawal: "Withdrawal",
        finance: "Finance",
        technical: "Technical",
        verification: "Verification",
        general: "General",
      },
    },
    campaign: {
      title: "Campaigns",
      description:
        "Growth and incentive campaigns for trading, deposit, and referral programs, with operational visibility into participation and payout readiness.",
      totalCampaigns: "Total Campaigns",
      activeCampaigns: "Active Campaigns",
      scheduledCampaigns: "Scheduled Campaigns",
      totalParticipants: "Total Participants",
      listTitle: "Campaigns",
      listDescription:
        "Review campaigns, reward structure, participants, and payout posture in one operational table.",
      searchPlaceholder: "Search campaigns by name, type, reward, or status",
      noCampaigns: "No campaigns match the current search and filters.",
      campaignName: "Campaign Name",
      type: "Type",
      rewardType: "Reward Type",
      participants: "Participants",
      startEnd: "Start / End",
      rules: "Rules",
      rewards: "Rewards",
      payout: "Payout",
      participantSummary: "Participant Summary",
      payoutStatus: "Payout Status",
      statuses: {
        active: "Active",
        scheduled: "Scheduled",
        ended: "Ended",
      },
      types: {
        trading: "Trading",
        deposit: "Deposit",
        referral: "Referral",
      },
    },
    referral: {
      title: "Referral",
      description:
        "Referral and invite rebate overview for operator review, with a lightweight read-first view of current incentive programs.",
      listTitle: "Referral Programs",
      listDescription:
        "Review current referral-focused incentive programs and their operational readiness in one lightweight panel.",
      status: "Status",
    },
    settings: {
      title: "Settings",
      description:
        "System configuration and business rule controls for commission processing, IB relationships, import standards, finance operations, and platform governance.",
      sectionsTitle: "Configuration Areas",
      sectionsDescription:
        "Review the current operating configuration across core business rules and system controls. This page remains read-first in preview mode.",
      general: "General",
      commissionRules: "Commission Rules",
      ibConfiguration: "IB Configuration",
      dataImport: "Data & Import",
      financeSettings: "Finance Settings",
      notifications: "Notifications",
      security: "Security",
      fields: {
        platformTimezone: "Platform Timezone",
        defaultCurrency: "Default Currency",
        adminLocaleFallback: "Admin Locale Fallback",
        adminFeeFloor: "Admin Fee Floor",
        l2Priority: "L2 Priority",
        batchApprovalMode: "Batch Approval Mode",
        maxReferralDepth: "Max Referral Depth",
        traderModel: "Trader / L1 / L2 Model",
        snapshotBehavior: "Snapshot Behavior",
        commissionFormats: "Commission Formats",
        columnMapping: "Column Mapping",
        validationMode: "Validation Mode",
        ledgerPosting: "Ledger Posting",
        withdrawalReview: "Withdrawal Review",
        reconciliationWindow: "Reconciliation Window",
        adminAlerts: "Admin Alerts",
        batchReviewNotices: "Batch Review Notices",
        financeExceptionNotices: "Finance Exception Notices",
        adminSessions: "Admin Sessions",
        auditVisibility: "Audit Visibility",
        sensitiveActions: "Sensitive Actions",
      },
    },
  },
  zh: {
    common: {
      nav: {
        dashboard: "仪表盘",
        users: "用户",
        accounts: "交易账户",
        brokers: "券商",
        campaigns: "活动",
        campaign: "活动",
        commission: "佣金中心",
        finance: "财务",
        network: "IB 覆盖",
        referral: "邀请返佣",
        promotions: "邀请返佣",
        support: "支持工单",
        settings: "系统设置",
      },
      shell: {
        globalSearchLabel: "全局搜索",
        searchPlaceholder: "搜索用户、账户、批次或提现...",
        alerts: "提醒",
        admin: "管理员",
        environment: "环境",
        previewMode: "预览模式",
        english: "EN",
        chinese: "中文",
        light: "浅色",
        dark: "深色",
      },
      actions: {
        clear: "清除",
        viewUser: "查看用户",
        viewAccount: "查看账户",
        viewCommission: "查看佣金",
        viewFinance: "查看财务",
        viewCoverage: "查看覆盖范围",
        viewNetworkSnapshot: "查看关系快照",
        batchApprove: "批量批准",
        batchReject: "批量拒绝",
        updatePlaceholder: "更新占位配置",
        postAdjustment: "记入调整",
      },
      labels: {
        search: "搜索",
        overview: "概览",
        contextRelationship: "上下文 / 关系",
        relatedActivityReferences: "相关活动 / 引用",
        handoff: "跳转",
        accountId: "账户 ID",
        broker: "券商",
        status: "状态",
        createdAt: "创建时间",
        updatedAt: "更新时间",
        validation: "校验",
        category: "分类",
        current: "当前",
        historical: "历史",
        currentSnapshot: "当前快照",
        historicalSnapshot: "历史快照",
        relationshipSnapshotId: "关系快照 ID",
        snapshotId: "快照 ID",
        snapshotCode: "快照编码",
        snapshotStatus: "快照状态",
        effectiveFrom: "生效开始",
        effectiveTo: "生效结束",
        relationshipDepth: "关系层级",
        timelinePreview: "时间线预览",
      },
      filters: {
        allStatuses: "全部状态",
        allCategories: "全部分类",
        allBrokers: "全部券商",
      },
      empty: {
        dash: "—",
      },
    },
    account: {
      title: "交易账户",
      description:
        "以账户为核心的运营中心，用于查看所有权、券商上下文，以及贯穿下游佣金与财务流程的 IB 关系快照。",
      totalAccounts: "账户总数",
      activeAccounts: "活跃账户",
      accountsWithL2: "含 L2 的账户",
      brokersCovered: "覆盖券商",
      directoryTitle: "交易账户目录",
      directoryDescription:
        "跨券商搜索全部交易账户，优先查看账户身份，再查看所有者与绑定到账户的 L1/L2 关系，而不是误解为用户层级结构。",
      overviewDescription: "Trading Accounts 是账户级关系与审计上下文的主要入口。",
      relationshipDescription:
        "此快照绑定在交易账户上。下游佣金、返佣与财务记录都遵循生成时捕获的关系快照。",
      historyDescription: "关系更新只影响未来记录，历史版本保持不变。",
      historyHighlightedSuffix: "与深链匹配的快照会在下方高亮显示。",
      activityDescription:
        "将该账户作为运营锚点，用于查看下游佣金说明、返佣记录、财务流水与提现操作。",
      handoffDescription:
        "以该账户作为中心运营枢纽，向上可回到所有者，向下可进入佣金与财务模块。",
      owner: "所有者 / 用户",
      userId: "用户 ID",
      accountType: "账户类型",
      traderUserIdOnAccount: "账户上的交易员用户 ID",
      relationshipSnapshot: "关系快照",
      snapshotHistory: "快照历史",
      relatedActivity: "相关活动",
      relationshipRoles: "关系角色",
      trader: "交易员",
      l1Ib: "L1 IB",
      l2Ib: "L2 IB",
      active: "活跃",
      monitoring: "监控中",
      suspended: "已暂停",
      traderOnly: "仅交易员",
      hasL1: "含 L1",
      hasL2: "含 L2",
      traderAccountSearchPlaceholder: "按账户、所有者、交易员、快照或 IB 搜索",
      noAccounts: "当前搜索与筛选条件下没有匹配的交易账户。",
      commissionCount: "佣金",
      rebateCount: "返佣",
      financeCount: "财务",
      withdrawalCount: "提现",
    },
    network: {
      title: "IB 覆盖",
      description:
        "查看以 IB 为中心的覆盖范围，包括直客账户、某个 L2 之下的 L1 IB，以及当前账户级覆盖足迹。",
      explorerTitle: "IB 覆盖浏览器",
      explorerDescription:
        "Network 专注于 IB 覆盖范围、下线可见性以及当前账户级覆盖足迹。历史账户关系检查归属 Trading Accounts。",
      helper:
        "此视图仅反映当前账户级 IB 覆盖范围；历史关系检查请前往 Trading Accounts。",
      searchIb: "搜索 IB",
      searchPlaceholder: "搜索 IB 用户 ID 或名称",
      ibSelection: "IB 选择",
      selectedIb: "当前 IB",
      currentIb: "当前 IB",
      previousIb: "上一级 IB",
      backToPreviousIb: "返回上一级 IB",
      noIbSelected: "未选择 IB",
      unknownIb: "未知 IB",
      directClientAccounts: "直客账户",
      coveredL1Ibs: "覆盖的 L1 IB",
      totalCoveredAccounts: "覆盖账户总数",
      activeCoveredAccounts: "活跃覆盖账户",
      upstreamL2Context: "上游 L2 上下文",
      upstreamL2Description:
        "显示所选 IB 作为 L1 时，在其覆盖账户中关联到的不同 L2 IB。",
      upstreamL2Empty: "当前覆盖数据中，此 IB 没有关联的上游 L2 上下文。",
      directClientsDescription:
        "所选 IB 作为直接 L1 关系拥有者的账户。点击行可打开对应账户与快照上下文。",
      l1UnderL2Title: "该 L2 之下的 L1 IB",
      l1UnderL2Description:
        "这些 L1 IB 的覆盖账户当前汇总到所选 IB（作为 L2）。点击行可切换到该 L1 的覆盖视图。",
      noDirectClients: "所选 IB 下没有直客账户。",
      noCoveredL1s: "所选 IB 下没有覆盖的 L1 IB。",
      noCoverage: "当前模拟数据中没有可用的 IB 关系覆盖数据。",
      directClientAccountLabel: "直客账户",
      coveredAccounts: "覆盖账户",
      activeAccounts: "活跃账户",
      snapshotStatus: "快照状态",
    },
    finance: {
      title: "财务",
      description: "下游财务工作区，用于查看已记录条目、提现审批、调整和对账。",
      modulesTitle: "财务模块",
      modulesDescription:
        "在财务模块中查看已入账记录、审批运营提现、管理调整，并与佣金结果进行对账。",
      totalLedgerAmount: "流水总额",
      pendingWithdrawals: "待处理提现",
      adjustmentsThisMonth: "本月调整",
      reconciliationAlerts: "对账提醒",
      withdrawals: "提现",
      ledger: "流水",
      adjustments: "调整",
      reconciliation: "对账",
      ledgerTitle: "流水",
      ledgerDescription: "用于审计查看的不可变财务记录，以及下游返佣引用和已记录操作。",
      ledgerPanelTitle: "流水记录",
      ledgerPanelDescription: "财务流水一旦写入即为不可变记录，是佣金输出的下游记录层。",
      ledgerFooter: "仅用于审计与对账的不可变记录视图。",
      postedEntries: "已入账",
      pendingEntries: "待处理",
      reversedEntries: "已冲销",
      withdrawalsTitle: "提现",
      withdrawalsDescription: "提现审批列表与请求审核占位控制。",
      withdrawalPanelTitle: "提现审批列表",
      withdrawalPanelDescription: "待处理、已批准和已拒绝表示提现申请的运营审核状态。",
      withdrawalPanelNote: "审批控件仅为占位流程，不会在当前模拟流程中写入真实财务更新。",
      approvalVolume: "审批金额",
      gasFees: "Gas 费用",
      rejected: "已拒绝",
      gasFeeConfiguration: "Gas 费用配置",
      defaultFee: "默认值",
      networkLabel: "网络",
      updatedLabel: "更新时间",
      placeholderOnly: "仅为占位展示。此控件目前不会提交真实财务变更。",
      modules: {
        withdrawals: "查看提现请求、批量动作和 Gas 费用占位设置。",
        ledger: "检查不可变财务记录和返佣关联条目。",
        adjustments: "查看手动余额调整和操作员备注。",
        reconciliation: "对比佣金输入、流水总额和支付差异。",
      },
    },
    commission: {
      title: "佣金中心",
      description: "查看券商佣金输入、校验拆分结果、进行模拟，并将最终记录交接到财务模块。",
      uploadCommission: "上传佣金",
      uploadTitle: "佣金上传",
      uploadDescription: "开始新的券商佣金导入流程。在创建批次之前，会先完成文件映射与校验。",
      uploadPlaceholderTitle: "上传区域",
      uploadPlaceholderDescription: "文件拖放、字段映射和校验控件将在下一轮工作流中接入。",
      supportedFormats: "支持格式：CSV、XLSX",
      mappingValidationNote: "在确认导入之前，会先完成字段映射与数据校验。",
      batchManagement: "批次管理",
      simulation: "模拟",
      clear: "清除",
      brokerInputs: "券商输入",
      commissionBreakdown: "佣金拆分",
      rebateRecords: "返佣记录",
      filteredByAccount: "按账户筛选",
      panelDescriptions: {
        inputs: "在校验和下游拆分前，先查看导入的券商输入。",
        allocation: "检查佣金拆分结果，并在抽屉中查看 waterfall 细节、关系上下文与财务交接。",
        rebates: "查看由佣金拆分流水线生成的最终返佣条目。",
      },
      searchPlaceholder: "搜索佣金 / 批次 / 券商 / 账户",
      summary: {
        totalCommission: "佣金总额",
        imported: "已导入",
        validated: "已校验",
        processed: "已处理",
        totalGross: "总毛佣",
        totalRebate: "返佣总额",
        totalPlatformShare: "平台分成总额",
        records: "记录数",
        totalPaid: "已支付总额",
        pending: "待处理",
        settled: "已结算",
      },
      helper: {
        inputStages: "导入、校验、处理表示下游拆分之前的上游佣金流水线阶段。",
        allocationStages: "导入、校验、处理表示下游财务记录之前的佣金流水线阶段。",
        rebatePipeline: "表示由佣金拆分生成的最终返佣条目。",
        rebateStates: "待处理、已入账和已冲销表示记入财务前后的返佣记录状态。",
        relationshipNote: "此佣金拆分遵循生成时捕获的账户级关系快照。",
      },
    },
    support: {
      title: "支持",
      description:
        "运营支持队列，用于查看工单、请求人上下文，并清晰跳转到关联的用户、交易账户、佣金和财务记录。",
      totalTickets: "工单总数",
      openTickets: "开放工单",
      inProgress: "处理中",
      resolved: "已解决",
      queueTitle: "支持队列",
      queueDescription:
        "查看支持工作负载，检查请求人和账户上下文，并在涉及具体用户或交易账户时进入相关运营模块。",
      searchPlaceholder: "按工单号、主题、请求人或账户搜索",
      noAccount: "无账户",
      noTickets: "当前搜索与筛选条件下没有匹配的支持工单。",
      subject: "主题",
      priority: "优先级",
      requester: "用户 / 请求人",
      relatedModule: "关联模块",
      ticketId: "工单 ID",
      overviewTitle: "概览",
      requesterLabel: "请求人",
      email: "邮箱",
      relatedContextTitle: "相关活动 / 引用",
      withdrawalId: "提现 ID",
      commissionId: "佣金 ID",
      rebateRecordId: "返佣记录 ID",
      ledgerRef: "流水引用",
      updatedAtNote: "最近活动记录于",
      statusOptions: {
        open: "开放",
        in_progress: "处理中",
        waiting_user: "等待用户",
        resolved: "已解决",
        closed: "已关闭",
      },
      categoryOptions: {
        account: "账户",
        commission: "佣金",
        rebate: "返佣",
        withdrawal: "提现",
        finance: "财务",
        technical: "技术",
        verification: "验证",
        general: "通用",
      },
    },
    campaign: {
      title: "活动",
      description:
        "用于管理交易、入金与推荐激励活动，帮助运营团队查看活动状态、参与情况与发放准备度。",
      totalCampaigns: "活动总数",
      activeCampaigns: "进行中活动",
      scheduledCampaigns: "待开始活动",
      totalParticipants: "参与人数",
      listTitle: "活动",
      listDescription:
        "在一个运营视图中查看活动状态、奖励结构、参与情况与发放准备情况。",
      searchPlaceholder: "搜索活动名称、类型、奖励或状态",
      noCampaigns: "当前搜索与筛选条件下没有匹配的活动。",
      campaignName: "活动名称",
      type: "类型",
      rewardType: "奖励类型",
      participants: "参与人数",
      startEnd: "开始 / 结束",
      rules: "规则",
      rewards: "奖励",
      payout: "发放",
      participantSummary: "参与概况",
      payoutStatus: "发放状态",
      statuses: {
        active: "进行中",
        scheduled: "待开始",
        ended: "已结束",
      },
      types: {
        trading: "交易",
        deposit: "入金",
        referral: "推荐",
      },
    },
    referral: {
      title: "邀请返佣",
      description:
        "用于查看推荐与邀请返佣相关的激励项目，帮助运营团队快速掌握当前活动状态。",
      listTitle: "返佣计划",
      listDescription: "在一个轻量视图中查看当前推荐返佣项目及其运营准备状态。",
      status: "状态",
    },
    settings: {
      title: "设置",
      description:
        "用于管理系统配置与业务规则，包括佣金处理、IB 关系、导入规范、财务参数与平台治理设置。",
      sectionsTitle: "配置分区",
      sectionsDescription:
        "查看当前平台核心业务规则与系统控制项。本页在预览模式下保持只读。",
      general: "常规",
      commissionRules: "佣金规则",
      ibConfiguration: "IB 配置",
      dataImport: "数据与导入",
      financeSettings: "财务设置",
      notifications: "通知",
      security: "安全",
      fields: {
        platformTimezone: "平台时区",
        defaultCurrency: "默认币种",
        adminLocaleFallback: "管理后台默认语言",
        adminFeeFloor: "平台管理费底线",
        l2Priority: "L2 分配优先级",
        batchApprovalMode: "批次审批方式",
        maxReferralDepth: "推荐层级上限",
        traderModel: "Trader / L1 / L2 模型",
        snapshotBehavior: "快照生效规则",
        commissionFormats: "佣金导入格式",
        columnMapping: "字段映射",
        validationMode: "校验模式",
        ledgerPosting: "流水入账规则",
        withdrawalReview: "提现审核方式",
        reconciliationWindow: "对账周期",
        adminAlerts: "管理提醒",
        batchReviewNotices: "批次审核通知",
        financeExceptionNotices: "财务异常通知",
        adminSessions: "管理会话",
        auditVisibility: "审计可见性",
        sensitiveActions: "敏感操作保护",
      },
    },
  },
} as const;

export function resolveAdminLanguage(value?: string | null): AdminLanguage {
  return value === "zh" ? "zh" : "en";
}

export function resolveAdminTheme(value?: string | null): AdminTheme {
  return value === "light" ? "light" : "dark";
}

export function adminT(lang: AdminLanguage, key: string): string {
  const segments = key.split(".");
  let current: unknown = adminTranslations[lang];

  for (const segment of segments) {
    if (typeof current !== "object" || current === null || !(segment in current)) {
      return key;
    }
    current = (current as Record<string, unknown>)[segment];
  }

  return typeof current === "string" ? current : key;
}
