import type { TradingAccountRecord, TradingAccountRelatedActivity } from "./_types";

export const MOCK_TRADING_ACCOUNTS: TradingAccountRecord[] = [
  {
    account_id: "AXI-001",
    user_id: "USR-1001",
    user_email: "alice@example.com",
    broker: "Axi",
    account_type: "standard",
    status: "active",
    trader_user_id: "USR-1001",
    l1_ib_id: "IB-L1-001",
    l2_ib_id: "IB-L2-014",
    created_at: "2026-01-12T09:30:00Z",
    relationship_snapshot_id: "REL-SNP-AXI-001-B",
    snapshot_code: "SNP-AXI-001-B",
    relationship_depth: "has_l2",
    relationship_snapshot_status: "active",
    relationship_effective_from: "2026-03-01T00:00:00Z",
    relationship_effective_to: null,
    relationship_is_current: true,
    relationship_history: [
      {
        relationship_snapshot_id: "REL-SNP-AXI-001-B",
        snapshot_code: "SNP-AXI-001-B",
        trader_user_id: "USR-1001",
        l1_ib_id: "IB-L1-001",
        l2_ib_id: "IB-L2-014",
        relationship_depth: "has_l2",
        snapshot_status: "active",
        effective_from: "2026-03-01T00:00:00Z",
        effective_to: null,
        is_current: true,
      },
      {
        relationship_snapshot_id: "REL-SNP-AXI-001-A",
        snapshot_code: "SNP-AXI-001-A",
        trader_user_id: "USR-1001",
        l1_ib_id: "IB-L1-001",
        l2_ib_id: "IB-L2-009",
        relationship_depth: "has_l2",
        snapshot_status: "inactive",
        effective_from: "2026-01-12T00:00:00Z",
        effective_to: "2026-02-28T23:59:59Z",
        is_current: false,
      },
    ],
  },
  {
    account_id: "TM-102",
    user_id: "USR-1002",
    user_email: "bob@example.com",
    broker: "Tickmill",
    account_type: "raw",
    status: "active",
    trader_user_id: "USR-1002",
    l1_ib_id: "IB-L1-003",
    l2_ib_id: null,
    created_at: "2026-01-18T11:15:00Z",
    relationship_snapshot_id: "REL-SNP-TM-102-A",
    snapshot_code: "SNP-TM-102-A",
    relationship_depth: "has_l1",
    relationship_snapshot_status: "active",
    relationship_effective_from: "2026-02-16T00:00:00Z",
    relationship_effective_to: null,
    relationship_is_current: true,
    relationship_history: [
      {
        relationship_snapshot_id: "REL-SNP-TM-102-A",
        snapshot_code: "SNP-TM-102-A",
        trader_user_id: "USR-1002",
        l1_ib_id: "IB-L1-003",
        l2_ib_id: null,
        relationship_depth: "has_l1",
        snapshot_status: "active",
        effective_from: "2026-02-16T00:00:00Z",
        effective_to: null,
        is_current: true,
      },
    ],
  },
  {
    account_id: "AXI-889",
    user_id: "USR-1003",
    user_email: "charlie@example.com",
    broker: "Axi",
    account_type: "pro",
    status: "monitoring",
    trader_user_id: "USR-1003",
    l1_ib_id: "IB-L1-008",
    l2_ib_id: "IB-L2-019",
    created_at: "2026-02-03T07:45:00Z",
    relationship_snapshot_id: "REL-SNP-AXI-889-A",
    snapshot_code: "SNP-AXI-889-A",
    relationship_depth: "has_l2",
    relationship_snapshot_status: "active",
    relationship_effective_from: "2026-02-03T00:00:00Z",
    relationship_effective_to: null,
    relationship_is_current: true,
    relationship_history: [
      {
        relationship_snapshot_id: "REL-SNP-AXI-889-A",
        snapshot_code: "SNP-AXI-889-A",
        trader_user_id: "USR-1003",
        l1_ib_id: "IB-L1-008",
        l2_ib_id: "IB-L2-019",
        relationship_depth: "has_l2",
        snapshot_status: "active",
        effective_from: "2026-02-03T00:00:00Z",
        effective_to: null,
        is_current: true,
      },
    ],
  },
  {
    account_id: "VT-440",
    user_id: "USR-1004",
    user_email: "diana@example.com",
    broker: "Vantage",
    account_type: "standard",
    status: "active",
    trader_user_id: "USR-1004",
    l1_ib_id: "IB-L1-011",
    l2_ib_id: null,
    created_at: "2026-02-10T13:20:00Z",
    relationship_snapshot_id: "REL-SNP-VT-440-A",
    snapshot_code: "SNP-VT-440-A",
    relationship_depth: "has_l1",
    relationship_snapshot_status: "pending",
    relationship_effective_from: "2026-03-25T00:00:00Z",
    relationship_effective_to: null,
    relationship_is_current: true,
    relationship_history: [
      {
        relationship_snapshot_id: "REL-SNP-VT-440-A",
        snapshot_code: "SNP-VT-440-A",
        trader_user_id: "USR-1004",
        l1_ib_id: "IB-L1-011",
        l2_ib_id: null,
        relationship_depth: "has_l1",
        snapshot_status: "pending",
        effective_from: "2026-03-25T00:00:00Z",
        effective_to: null,
        is_current: true,
      },
    ],
  },
  {
    account_id: "ICM-221",
    user_id: "USR-1005",
    user_email: "evan@example.com",
    broker: "IC Markets",
    account_type: "raw",
    status: "suspended",
    trader_user_id: "USR-1005",
    l1_ib_id: "IB-L1-015",
    l2_ib_id: "IB-L2-022",
    created_at: "2026-02-22T15:05:00Z",
    relationship_snapshot_id: "REL-SNP-ICM-221-A",
    snapshot_code: "SNP-ICM-221-A",
    relationship_depth: "has_l2",
    relationship_snapshot_status: "inactive",
    relationship_effective_from: "2025-12-01T00:00:00Z",
    relationship_effective_to: null,
    relationship_is_current: true,
    relationship_history: [
      {
        relationship_snapshot_id: "REL-SNP-ICM-221-A",
        snapshot_code: "SNP-ICM-221-A",
        trader_user_id: "USR-1005",
        l1_ib_id: "IB-L1-015",
        l2_ib_id: "IB-L2-022",
        relationship_depth: "has_l2",
        snapshot_status: "inactive",
        effective_from: "2025-12-01T00:00:00Z",
        effective_to: null,
        is_current: true,
      },
    ],
  },
];

export const MOCK_ACCOUNT_ACTIVITY_SUMMARY: Record<string, TradingAccountRelatedActivity> = {
  "AXI-001": {
    commission_records: 14,
    rebate_records: 12,
    finance_entries: 9,
    withdrawals: 1,
  },
  "TM-102": {
    commission_records: 10,
    rebate_records: 8,
    finance_entries: 6,
    withdrawals: 2,
  },
  "AXI-889": {
    commission_records: 7,
    rebate_records: 7,
    finance_entries: 5,
    withdrawals: 0,
  },
  "VT-440": {
    commission_records: 11,
    rebate_records: 9,
    finance_entries: 7,
    withdrawals: 1,
  },
  "ICM-221": {
    commission_records: 4,
    rebate_records: 3,
    finance_entries: 3,
    withdrawals: 1,
  },
};
