import type { AccountNetworkDetail, AccountNetworkRow } from "@/types/network";

export const MOCK_ACCOUNT_NETWORK_SNAPSHOTS: AccountNetworkDetail[] = [
  {
    id: "REL-SNP-1991",
    snapshotCode: "SNP-1991",
    accountId: "ACC-9001",
    accountCode: "AXI-9001",
    brokerName: "Axi",
    trader: {
      userId: "USR-1001",
      name: "Alice Tan",
      email: "alice@example.com",
    },
    l1: {
      userId: "IB-2101",
      name: "Marcus Lim",
      email: "marcus.lim@finhalo.test",
    },
    l2: {
      userId: "IB-3099",
      name: "Daniel Goh",
      email: "daniel.goh@finhalo.test",
    },
    relationshipDepth: "has_l2",
    effectiveFrom: "2026-01-12T00:00:00Z",
    effectiveTo: "2026-02-28T23:59:59Z",
    status: "inactive",
    source: "manual_update",
    changeReason: "Superseded by future L2 reassignment.",
    createdBy: "ops.network",
    createdAt: "2026-01-11T12:05:00Z",
    isCurrent: false,
    updatedAt: "2026-02-28T16:40:00Z",
    history: [
      {
        id: "HIS-5001",
        accountId: "ACC-9001",
        changeType: "assign",
        newTraderName: "Alice Tan",
        newL1Name: "Marcus Lim",
        newL2Name: "Daniel Goh",
        effectiveFrom: "2026-01-12T00:00:00Z",
        createdAt: "2026-01-11T12:05:00Z",
        changedBy: "ops.network",
      },
    ],
  },
  {
    id: "REL-SNP-2001",
    snapshotCode: "SNP-2001",
    accountId: "ACC-9001",
    accountCode: "AXI-9001",
    brokerName: "Axi",
    trader: {
      userId: "USR-1001",
      name: "Alice Tan",
      email: "alice@example.com",
    },
    l1: {
      userId: "IB-2101",
      name: "Marcus Lim",
      email: "marcus.lim@finhalo.test",
    },
    l2: {
      userId: "IB-3102",
      name: "Cheryl Wong",
      email: "cheryl.wong@finhalo.test",
    },
    relationshipDepth: "has_l2",
    status: "active",
    effectiveTo: null,
    source: "manual_update",
    changeReason: "Updated future rebate chain after partner migration.",
    createdBy: "ops.network",
    createdAt: "2026-02-28T16:40:00Z",
    isCurrent: true,
    effectiveFrom: "2026-03-01T00:00:00Z",
    updatedAt: "2026-03-20T09:15:00Z",
    history: [
      {
        id: "HIS-5003",
        accountId: "ACC-9001",
        changeType: "replace_l2",
        oldL2Name: "Daniel Goh",
        newL2Name: "Cheryl Wong",
        effectiveFrom: "2026-03-01T00:00:00Z",
        createdAt: "2026-02-28T16:40:00Z",
        changedBy: "ops.network",
        note: "Updated future rebate chain after partner migration.",
      },
      {
        id: "HIS-5001",
        accountId: "ACC-9001",
        changeType: "assign",
        newTraderName: "Alice Tan",
        newL1Name: "Marcus Lim",
        newL2Name: "Daniel Goh",
        effectiveFrom: "2026-01-12T00:00:00Z",
        createdAt: "2026-01-11T12:05:00Z",
        changedBy: "ops.network",
      },
    ],
  },
  {
    id: "REL-SNP-2002",
    snapshotCode: "SNP-2002",
    accountId: "ACC-9002",
    accountCode: "TM-2044",
    brokerName: "Tickmill",
    trader: {
      userId: "USR-1002",
      name: "Brian Koh",
      email: "brian@example.com",
    },
    l1: {
      userId: "IB-2104",
      name: "Hannah Lee",
      email: "hannah.lee@finhalo.test",
    },
    l2: null,
    relationshipDepth: "has_l1",
    status: "active",
    effectiveTo: null,
    source: "manual_update",
    changeReason: "Removed L2 for future commission cycles.",
    createdBy: "ops.network",
    createdAt: "2026-02-15T10:32:00Z",
    isCurrent: true,
    effectiveFrom: "2026-02-16T00:00:00Z",
    updatedAt: "2026-03-18T07:10:00Z",
    history: [
      {
        id: "HIS-5012",
        accountId: "ACC-9002",
        changeType: "remove_l2",
        oldL2Name: "Kelvin Chia",
        effectiveFrom: "2026-02-16T00:00:00Z",
        createdAt: "2026-02-15T10:32:00Z",
        changedBy: "ops.network",
        note: "Future cycles no longer route through L2 for this account.",
      },
      {
        id: "HIS-5010",
        accountId: "ACC-9002",
        changeType: "assign",
        newTraderName: "Brian Koh",
        newL1Name: "Hannah Lee",
        newL2Name: "Kelvin Chia",
        effectiveFrom: "2026-01-05T00:00:00Z",
        createdAt: "2026-01-04T09:18:00Z",
        changedBy: "ops.network",
      },
    ],
  },
  {
    id: "REL-SNP-2003",
    snapshotCode: "SNP-2003",
    accountId: "ACC-9003",
    accountCode: "IC-3110",
    brokerName: "IC Markets",
    trader: {
      userId: "USR-1003",
      name: "Carla Ong",
      email: "carla@example.com",
    },
    l1: null,
    l2: null,
    relationshipDepth: "trader_only",
    status: "pending",
    effectiveTo: null,
    source: "initial_assignment",
    changeReason: "Pending first commission batch under new relationship snapshot.",
    createdBy: "ops.network",
    createdAt: "2026-03-22T11:45:00Z",
    isCurrent: true,
    effectiveFrom: "2026-03-25T00:00:00Z",
    updatedAt: "2026-03-22T11:45:00Z",
    history: [
      {
        id: "HIS-5030",
        accountId: "ACC-9003",
        changeType: "assign",
        newTraderName: "Carla Ong",
        effectiveFrom: "2026-03-25T00:00:00Z",
        createdAt: "2026-03-22T11:45:00Z",
        changedBy: "ops.network",
        note: "Pending first commission batch under new relationship snapshot.",
      },
    ],
  },
  {
    id: "REL-SNP-2004",
    snapshotCode: "SNP-2004",
    accountId: "ACC-9004",
    accountCode: "PEP-1188",
    brokerName: "Pepperstone",
    trader: {
      userId: "USR-1004",
      name: "Derek Yeo",
      email: "derek@example.com",
    },
    l1: {
      userId: "IB-2107",
      name: "Rina Chew",
      email: "rina.chew@finhalo.test",
    },
    l2: {
      userId: "IB-3108",
      name: "Samuel Ho",
      email: "samuel.ho@finhalo.test",
    },
    relationshipDepth: "has_l2",
    status: "inactive",
    effectiveTo: null,
    source: "manual_update",
    changeReason: "Account currently inactive with last snapshot retained for audit tracing.",
    createdBy: "ops.network",
    createdAt: "2026-01-30T14:12:00Z",
    isCurrent: true,
    effectiveFrom: "2025-12-01T00:00:00Z",
    updatedAt: "2026-03-10T05:55:00Z",
    history: [
      {
        id: "HIS-5045",
        accountId: "ACC-9004",
        changeType: "replace_l1",
        oldL1Name: "Elaine Pang",
        newL1Name: "Rina Chew",
        effectiveFrom: "2026-02-01T00:00:00Z",
        createdAt: "2026-01-30T14:12:00Z",
        changedBy: "ops.network",
      },
      {
        id: "HIS-5042",
        accountId: "ACC-9004",
        changeType: "assign",
        newTraderName: "Derek Yeo",
        newL1Name: "Elaine Pang",
        newL2Name: "Samuel Ho",
        effectiveFrom: "2025-12-01T00:00:00Z",
        createdAt: "2025-11-29T08:20:00Z",
        changedBy: "ops.network",
      },
    ],
  },
  {
    id: "REL-SNP-2005",
    snapshotCode: "SNP-2005",
    accountId: "ACC-9005",
    accountCode: "EXN-5521",
    brokerName: "Exness",
    trader: {
      userId: "USR-1005",
      name: "Emily Tan",
      email: "emily@example.com",
    },
    l1: {
      userId: "IB-2111",
      name: "Jason Loke",
      email: "jason.loke@finhalo.test",
    },
    l2: null,
    relationshipDepth: "has_l1",
    status: "active",
    effectiveTo: null,
    source: "initial_assignment",
    changeReason: "Initial account-level IB assignment.",
    createdBy: "ops.network",
    createdAt: "2026-02-19T15:16:00Z",
    isCurrent: true,
    effectiveFrom: "2026-02-20T00:00:00Z",
    updatedAt: "2026-03-19T13:22:00Z",
    history: [
      {
        id: "HIS-5050",
        accountId: "ACC-9005",
        changeType: "assign",
        newTraderName: "Emily Tan",
        newL1Name: "Jason Loke",
        effectiveFrom: "2026-02-20T00:00:00Z",
        createdAt: "2026-02-19T15:16:00Z",
        changedBy: "ops.network",
      },
    ],
  },
];

export const MOCK_ACCOUNT_NETWORK_DETAILS = MOCK_ACCOUNT_NETWORK_SNAPSHOTS.filter(
  (detail) => detail.isCurrent
);

export const MOCK_ACCOUNT_NETWORK_ROWS: AccountNetworkRow[] = MOCK_ACCOUNT_NETWORK_DETAILS.map(
  (detail) => ({
    id: detail.id,
    accountId: detail.accountId,
    accountCode: detail.accountCode,
    relationship_snapshot_id: detail.id,
    brokerId: detail.brokerName.toLowerCase().replace(/\s+/g, "-"),
    brokerName: detail.brokerName,
    traderUserId: detail.trader.userId,
    traderName: detail.trader.name,
    l1UserId: detail.l1?.userId ?? null,
    l1Name: detail.l1?.name ?? null,
    l2UserId: detail.l2?.userId ?? null,
    l2Name: detail.l2?.name ?? null,
    relationshipDepth: detail.relationshipDepth,
    status: detail.status,
    effectiveFrom: detail.effectiveFrom,
    effectiveTo: detail.effectiveTo ?? null,
    updatedAt: detail.updatedAt,
  })
);
