import type {
  SupportAnnouncement,
  SupportOutboundMessage,
  SupportTicket,
  SupportTicketTimelineItem,
} from "./_types";

export const MOCK_SUPPORT_TICKETS: SupportTicket[] = [
  {
    ticket_id: "TCK-4101",
    subject: "Withdrawal still pending after approval window",
    category: "withdrawal",
    priority: "high",
    status: "open",
    user_id: "USR-1001",
    user_email: "alice@example.com",
    account_id: "AXI-001",
    related_module: "withdrawals",
    withdrawal_id: "WDR-4101",
    created_at: "2026-03-19T10:50:00Z",
    updated_at: "2026-03-23T09:12:00Z",
  },
  {
    ticket_id: "TCK-4102",
    subject: "Commission breakdown does not match broker statement",
    category: "commission",
    priority: "urgent",
    status: "in_progress",
    user_id: "USR-1002",
    user_email: "bob@example.com",
    account_id: "TM-102",
    related_module: "commission",
    commission_id: "COM-22014",
    rebate_record_id: "RBT-1002",
    created_at: "2026-03-20T08:35:00Z",
    updated_at: "2026-03-23T08:20:00Z",
  },
  {
    ticket_id: "TCK-4103",
    subject: "Need account verification re-check",
    category: "verification",
    priority: "medium",
    status: "waiting_user",
    user_id: "USR-1004",
    user_email: "diana@example.com",
    account_id: "VT-440",
    related_module: "verification",
    created_at: "2026-03-18T16:10:00Z",
    updated_at: "2026-03-22T14:05:00Z",
  },
  {
    ticket_id: "TCK-4104",
    subject: "Ledger entry posted without expected note",
    category: "finance",
    priority: "medium",
    status: "resolved",
    user_id: "USR-1003",
    user_email: "charlie@example.com",
    account_id: "AXI-889",
    related_module: "finance",
    ledger_ref: "LED-20260321-1003",
    rebate_record_id: "RBT-1003",
    created_at: "2026-03-17T12:00:00Z",
    updated_at: "2026-03-21T16:42:00Z",
  },
  {
    ticket_id: "TCK-4105",
    subject: "Unable to load reports from admin dashboard",
    category: "technical",
    priority: "low",
    status: "closed",
    user_id: "USR-1006",
    user_email: "fiona@example.com",
    account_id: null,
    related_module: "technical",
    created_at: "2026-03-15T09:22:00Z",
    updated_at: "2026-03-18T11:10:00Z",
  },
];

export const MOCK_SUPPORT_TICKET_TIMELINE: Record<string, SupportTicketTimelineItem[]> = {
  "TCK-4101": [
    {
      message_id: "MSG-8101",
      ticket_id: "TCK-4101",
      author_type: "user",
      author_name: "alice@example.com",
      body: "I requested a withdrawal yesterday and it is still pending in the app.",
      created_at: "2026-03-19T10:52:00Z",
    },
    {
      message_id: "MSG-8102",
      ticket_id: "TCK-4101",
      author_type: "admin",
      author_name: "Operations Desk",
      body: "We are checking the withdrawal approval queue and the linked account context now.",
      created_at: "2026-03-19T11:15:00Z",
    },
  ],
  "TCK-4102": [
    {
      message_id: "MSG-8103",
      ticket_id: "TCK-4102",
      author_type: "user",
      author_name: "bob@example.com",
      body: "The broker statement and the commission result view are showing different totals for my account.",
      created_at: "2026-03-20T08:37:00Z",
    },
    {
      message_id: "MSG-8104",
      ticket_id: "TCK-4102",
      author_type: "admin",
      author_name: "Commission Review",
      body: "We have linked this ticket to the account-level commission breakdown for review.",
      created_at: "2026-03-20T09:05:00Z",
    },
    {
      message_id: "MSG-8105",
      ticket_id: "TCK-4102",
      author_type: "system",
      author_name: "System",
      body: "Ticket linked to rebate record RBT-1002 for downstream finance traceability.",
      created_at: "2026-03-20T09:12:00Z",
    },
  ],
  "TCK-4103": [
    {
      message_id: "MSG-8106",
      ticket_id: "TCK-4103",
      author_type: "admin",
      author_name: "Verification Team",
      body: "Please upload the latest proof of identity document for the linked trading account.",
      created_at: "2026-03-18T16:22:00Z",
    },
  ],
  "TCK-4104": [
    {
      message_id: "MSG-8107",
      ticket_id: "TCK-4104",
      author_type: "user",
      author_name: "charlie@example.com",
      body: "I can see the ledger record, but I expected a clearer payout note on the finance side.",
      created_at: "2026-03-17T12:03:00Z",
    },
    {
      message_id: "MSG-8108",
      ticket_id: "TCK-4104",
      author_type: "admin",
      author_name: "Finance Ops",
      body: "The immutable finance record has been reviewed and the entry note has been clarified internally.",
      created_at: "2026-03-21T16:30:00Z",
    },
  ],
  "TCK-4105": [
    {
      message_id: "MSG-8109",
      ticket_id: "TCK-4105",
      author_type: "system",
      author_name: "System",
      body: "Incident resolved after dashboard cache was refreshed.",
      created_at: "2026-03-18T10:48:00Z",
    },
  ],
};

export const MOCK_SUPPORT_ANNOUNCEMENTS: SupportAnnouncement[] = [
  {
    announcement_id: "ANN-2001",
    title: "Scheduled Withdrawal Review Window",
    body: "Withdrawal approvals will run with extended review checks between 02:00 and 03:00 UTC.",
    status: "published",
    created_at: "2026-03-27T02:10:00Z",
    created_by: "Support Admin",
  },
  {
    announcement_id: "ANN-2002",
    title: "Commission Import Maintenance",
    body: "Commission import is under maintenance for broker mapping updates this weekend.",
    status: "published",
    created_at: "2026-03-26T09:30:00Z",
    created_by: "Operations Desk",
  },
];

export const MOCK_SUPPORT_OUTBOUND_MESSAGES: SupportOutboundMessage[] = [
  {
    message_id: "ADM-MSG-3001",
    target_user_id: "USR-1002",
    target_email: "bob@example.com",
    subject: "Commission Case Update",
    body: "Your commission discrepancy case is now under finance validation. We will update you again within one cycle.",
    created_at: "2026-03-27T05:40:00Z",
    sent_by: "Support Admin",
  },
  {
    message_id: "ADM-MSG-3002",
    target_user_id: null,
    target_email: "alice@example.com",
    subject: "Withdrawal Queue Notice",
    body: "Your withdrawal request remains in manual review due to compliance checks and will be prioritized in the next run.",
    created_at: "2026-03-26T13:25:00Z",
    sent_by: "Support Admin",
  },
];
