-- Phase 3 Task 2: Withdrawal System
-- Additive migration for withdrawal workflow, risk controls, and ledger-safe idempotent processing.

create table if not exists public.withdrawal_requests (
  withdrawal_id text primary key,
  user_id text not null,
  account_id text,
  request_amount numeric(20,8) not null check (request_amount > 0),
  fee_amount numeric(20,8) not null default 0 check (fee_amount >= 0),
  net_amount numeric(20,8) not null check (net_amount >= 0),
  currency text not null default 'USD',
  wallet_address text not null,
  payout_method text not null default 'wallet_transfer',
  status text not null default 'requested',
  requested_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by text,
  processed_at timestamptz,
  processed_by text,
  rejection_reason text,
  review_notes text,
  reserve_ledger_ref text,
  release_ledger_ref text,
  payout_ledger_ref text,
  idempotency_key text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'withdrawal_requests_status_check'
  ) then
    alter table public.withdrawal_requests
      add constraint withdrawal_requests_status_check
      check (
        status in (
          'requested',
          'under_review',
          'approved',
          'rejected',
          'processing',
          'completed',
          'failed',
          'cancelled'
        )
      );
  end if;
end $$;

create index if not exists withdrawal_requests_user_status_idx
  on public.withdrawal_requests (user_id, status, requested_at desc);

create index if not exists withdrawal_requests_account_status_idx
  on public.withdrawal_requests (account_id, status, requested_at desc);

create unique index if not exists withdrawal_requests_user_idempotency_uidx
  on public.withdrawal_requests (user_id, idempotency_key)
  where idempotency_key is not null;

create table if not exists public.withdrawal_request_events (
  event_id bigint generated by default as identity primary key,
  withdrawal_id text not null references public.withdrawal_requests (withdrawal_id) on delete cascade,
  previous_status text,
  next_status text not null,
  actor text,
  reason text,
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists withdrawal_request_events_withdrawal_created_idx
  on public.withdrawal_request_events (withdrawal_id, created_at desc);

alter table if exists public.finance_ledger
  add column if not exists related_withdrawal_id text;

alter table if exists public.finance_ledger
  add column if not exists memo text;

alter table if exists public.finance_ledger
  add column if not exists currency text;

create unique index if not exists finance_ledger_withdrawal_reference_uidx
  on public.finance_ledger (reference_type, reference_id)
  where reference_type = 'withdrawal'
    and reference_id is not null;

create index if not exists finance_ledger_related_withdrawal_idx
  on public.finance_ledger (related_withdrawal_id, created_at desc);

create or replace function public.finhalo_assert_withdrawal_ledger_entry(
  p_reference_id text,
  p_related_withdrawal_id text,
  p_user_id text,
  p_account_id text,
  p_transaction_type text,
  p_direction text,
  p_status text,
  p_amount numeric,
  p_currency text
)
returns void
language plpgsql
stable
as $$
declare
  v_row jsonb;
  v_amount numeric(20,8);
  v_existing_account_id text;
begin
  select to_jsonb(fl)
  into v_row
  from public.finance_ledger as fl
  where fl.reference_type = 'withdrawal'
    and fl.reference_id = p_reference_id
  limit 1;

  if v_row is null then
    raise exception 'Missing withdrawal ledger row for reference_id %.', p_reference_id;
  end if;

  v_amount := coalesce((v_row ->> 'amount')::numeric, 0);
  if abs(v_amount - abs(coalesce(p_amount, 0))) > 0.00000100 then
    raise exception 'Withdrawal ledger mismatch for reference_id % (amount mismatch).', p_reference_id;
  end if;

  if lower(coalesce(v_row ->> 'transaction_type', v_row ->> 'entry_type', '')) <> lower(coalesce(p_transaction_type, '')) then
    raise exception 'Withdrawal ledger mismatch for reference_id % (transaction_type mismatch).', p_reference_id;
  end if;

  if lower(coalesce(v_row ->> 'direction', '')) <> lower(coalesce(p_direction, '')) then
    raise exception 'Withdrawal ledger mismatch for reference_id % (direction mismatch).', p_reference_id;
  end if;

  if lower(coalesce(v_row ->> 'status', '')) <> lower(coalesce(p_status, '')) then
    raise exception 'Withdrawal ledger mismatch for reference_id % (status mismatch).', p_reference_id;
  end if;

  if coalesce(v_row ->> 'user_id', '') <> coalesce(p_user_id, '') then
    raise exception 'Withdrawal ledger mismatch for reference_id % (user mismatch).', p_reference_id;
  end if;

  v_existing_account_id := coalesce(v_row ->> 'account_id', '');
  if v_existing_account_id <> coalesce(p_account_id, '') then
    raise exception 'Withdrawal ledger mismatch for reference_id % (account mismatch).', p_reference_id;
  end if;

  if coalesce(v_row ->> 'related_withdrawal_id', '') <> coalesce(p_related_withdrawal_id, '') then
    raise exception 'Withdrawal ledger mismatch for reference_id % (withdrawal linkage mismatch).', p_reference_id;
  end if;

  if upper(coalesce(v_row ->> 'currency', 'USD')) <> upper(coalesce(p_currency, 'USD')) then
    raise exception 'Withdrawal ledger mismatch for reference_id % (currency mismatch).', p_reference_id;
  end if;
end;
$$;

create or replace function public.finhalo_generate_withdrawal_id()
returns text
language sql
as $$
  select
    'WDR-' ||
    to_char(timezone('utc', now()), 'YYYYMMDDHH24MISSMS') ||
    '-' ||
    substr(md5(random()::text || clock_timestamp()::text), 1, 8);
$$;

create or replace function public.finhalo_get_user_posted_ledger_balance(
  p_user_id text,
  p_account_id text default null
)
returns numeric
language plpgsql
stable
as $$
declare
  v_balance numeric(20,8);
begin
  if p_user_id is null or btrim(p_user_id) = '' then
    return 0;
  end if;

  select coalesce(sum(
    case
      when lower(coalesce(fl.direction, 'credit')) = 'debit' then -abs(coalesce(fl.amount, 0))
      else abs(coalesce(fl.amount, 0))
    end
  ), 0)
  into v_balance
  from public.finance_ledger as fl
  where fl.user_id = p_user_id
    and (p_account_id is null or p_account_id = '' or fl.account_id = p_account_id)
    and lower(coalesce(fl.status, 'posted')) = 'posted';

  return coalesce(v_balance, 0);
end;
$$;

create or replace function public.finhalo_get_user_open_withdrawal_hold(
  p_user_id text,
  p_account_id text default null
)
returns numeric
language plpgsql
stable
as $$
declare
  v_reserved numeric(20,8);
begin
  if p_user_id is null or btrim(p_user_id) = '' then
    return 0;
  end if;

  select coalesce(sum(coalesce(wr.request_amount, 0)), 0)
  into v_reserved
  from public.withdrawal_requests as wr
  where wr.user_id = p_user_id
    and (p_account_id is null or p_account_id = '' or wr.account_id = p_account_id)
    and wr.status in ('requested', 'under_review', 'approved', 'processing');

  return coalesce(v_reserved, 0);
end;
$$;

create or replace function public.finhalo_get_user_withdrawable_balance(
  p_user_id text,
  p_account_id text default null
)
returns numeric
language plpgsql
stable
as $$
declare
  v_posted numeric(20,8);
  v_reserved numeric(20,8);
begin
  v_posted := public.finhalo_get_user_posted_ledger_balance(p_user_id, p_account_id);
  v_reserved := public.finhalo_get_user_open_withdrawal_hold(p_user_id, p_account_id);

  return v_posted - v_reserved;
end;
$$;

create or replace function public.client_create_withdrawal_request(
  p_user_id text,
  p_account_id text default null,
  p_request_amount numeric,
  p_fee_amount numeric default 0,
  p_currency text default 'USD',
  p_wallet_address text default '',
  p_payout_method text default 'wallet_transfer',
  p_idempotency_key text default null
)
returns table (
  withdrawal_id text,
  status text,
  request_amount numeric,
  fee_amount numeric,
  net_amount numeric,
  currency text,
  available_before numeric,
  available_after numeric
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request_amount numeric(20,8);
  v_fee_amount numeric(20,8);
  v_net_amount numeric(20,8);
  v_currency text;
  v_wallet text;
  v_method text;
  v_idempotency_key text;
  v_available_before numeric(20,8);
  v_available_after numeric(20,8);
  v_withdrawal_id text;
  v_reserve_ref text;
  v_reserve_ledger_ref text;
  v_existing record;
  v_affected_rows integer;
begin
  if p_user_id is null or btrim(p_user_id) = '' then
    raise exception 'user_id is required';
  end if;

  v_request_amount := round(coalesce(p_request_amount, 0), 8);
  v_fee_amount := round(greatest(coalesce(p_fee_amount, 0), 0), 8);
  v_currency := upper(coalesce(nullif(btrim(p_currency), ''), 'USD'));
  v_wallet := btrim(coalesce(p_wallet_address, ''));
  v_method := coalesce(nullif(btrim(p_payout_method), ''), 'wallet_transfer');
  v_idempotency_key := nullif(btrim(coalesce(p_idempotency_key, '')), '');

  if v_request_amount <= 0 then
    raise exception 'request_amount must be greater than 0';
  end if;

  if v_fee_amount > v_request_amount then
    raise exception 'fee_amount cannot exceed request_amount';
  end if;

  if v_wallet = '' then
    raise exception 'wallet_address is required';
  end if;

  perform pg_advisory_xact_lock(hashtext('withdrawal:' || p_user_id)::bigint);

  v_net_amount := round(v_request_amount - v_fee_amount, 8);

  if v_idempotency_key is not null then
    select
      wr.withdrawal_id,
      wr.status,
      wr.request_amount,
      wr.fee_amount,
      wr.net_amount,
      wr.currency
    into v_existing
    from public.withdrawal_requests as wr
    where wr.user_id = p_user_id
      and wr.idempotency_key = v_idempotency_key
    limit 1;

    if found then
      v_available_before := public.finhalo_get_user_withdrawable_balance(p_user_id, p_account_id);

      return query
      select
        v_existing.withdrawal_id::text,
        v_existing.status::text,
        v_existing.request_amount::numeric,
        v_existing.fee_amount::numeric,
        v_existing.net_amount::numeric,
        v_existing.currency::text,
        v_available_before::numeric,
        v_available_before::numeric;
      return;
    end if;
  end if;

  v_available_before := public.finhalo_get_user_withdrawable_balance(p_user_id, p_account_id);

  if v_available_before < v_request_amount then
    raise exception 'Insufficient withdrawable balance. available=%, request=%',
      v_available_before, v_request_amount;
  end if;

  v_withdrawal_id := public.finhalo_generate_withdrawal_id();
  v_reserve_ref := v_withdrawal_id || ':reserve';
  v_reserve_ledger_ref := 'LED-WDR-' || v_withdrawal_id || '-RESERVE';

  insert into public.withdrawal_requests (
    withdrawal_id,
    user_id,
    account_id,
    request_amount,
    fee_amount,
    net_amount,
    currency,
    wallet_address,
    payout_method,
    status,
    requested_at,
    idempotency_key,
    reserve_ledger_ref,
    created_at,
    updated_at
  )
  values (
    v_withdrawal_id,
    p_user_id,
    nullif(btrim(coalesce(p_account_id, '')), ''),
    v_request_amount,
    v_fee_amount,
    v_net_amount,
    v_currency,
    v_wallet,
    v_method,
    'requested',
    now(),
    v_idempotency_key,
    v_reserve_ledger_ref,
    now(),
    now()
  );

  insert into public.withdrawal_request_events (
    withdrawal_id,
    previous_status,
    next_status,
    actor,
    reason,
    notes,
    metadata,
    created_at
  )
  values (
    v_withdrawal_id,
    null,
    'requested',
    p_user_id,
    null,
    'Client submitted withdrawal request',
    jsonb_build_object(
      'request_amount', v_request_amount,
      'fee_amount', v_fee_amount,
      'net_amount', v_net_amount,
      'currency', v_currency,
      'payout_method', v_method
    ),
    now()
  );

  insert into public.finance_ledger (
    ledger_ref,
    reference_type,
    reference_id,
    related_withdrawal_id,
    transaction_type,
    entry_type,
    user_id,
    account_id,
    amount,
    direction,
    status,
    currency,
    memo,
    created_at
  )
  values (
    v_reserve_ledger_ref,
    'withdrawal',
    v_reserve_ref,
    v_withdrawal_id,
    'withdrawal_reserve',
    'withdrawal_reserve',
    p_user_id,
    nullif(btrim(coalesce(p_account_id, '')), ''),
    abs(v_request_amount),
    'debit',
    'pending',
    v_currency,
    'Withdrawal reserve hold',
    now()
  )
  on conflict (reference_type, reference_id) do nothing;

  get diagnostics v_affected_rows = row_count;
  if v_affected_rows = 0 then
    perform public.finhalo_assert_withdrawal_ledger_entry(
      v_reserve_ref,
      v_withdrawal_id,
      p_user_id,
      nullif(btrim(coalesce(p_account_id, '')), ''),
      'withdrawal_reserve',
      'debit',
      'pending',
      abs(v_request_amount),
      v_currency
    );
  end if;

  v_available_after := public.finhalo_get_user_withdrawable_balance(p_user_id, p_account_id);

  return query
  select
    v_withdrawal_id,
    'requested'::text,
    v_request_amount,
    v_fee_amount,
    v_net_amount,
    v_currency,
    v_available_before,
    v_available_after;
end;
$$;

create or replace function public.admin_transition_withdrawal_request(
  p_withdrawal_id text,
  p_next_status text,
  p_actor text default 'admin',
  p_reason text default null,
  p_notes text default null
)
returns table (
  withdrawal_id text,
  previous_status text,
  status text,
  reserve_ledger_ref text,
  release_ledger_ref text,
  payout_ledger_ref text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.withdrawal_requests%rowtype;
  v_previous_status text;
  v_next_status text;
  v_release_ref text;
  v_release_ledger_ref text;
  v_payout_ref text;
  v_payout_ledger_ref text;
  v_transition_allowed boolean := false;
  v_affected_rows integer;
begin
  if p_withdrawal_id is null or btrim(p_withdrawal_id) = '' then
    raise exception 'withdrawal_id is required';
  end if;

  v_next_status := lower(btrim(coalesce(p_next_status, '')));

  if v_next_status not in (
    'requested',
    'under_review',
    'approved',
    'rejected',
    'processing',
    'completed',
    'failed',
    'cancelled'
  ) then
    raise exception 'Invalid next status: %', v_next_status;
  end if;

  select *
  into v_request
  from public.withdrawal_requests
  where withdrawal_id = p_withdrawal_id
  for update;

  if not found then
    raise exception 'withdrawal % not found', p_withdrawal_id;
  end if;

  v_previous_status := v_request.status;

  if v_previous_status = v_next_status then
    return query
    select
      v_request.withdrawal_id,
      v_previous_status,
      v_request.status,
      v_request.reserve_ledger_ref,
      v_request.release_ledger_ref,
      v_request.payout_ledger_ref;
    return;
  end if;

  v_transition_allowed := (
    (v_previous_status = 'requested' and v_next_status in ('under_review', 'rejected', 'cancelled')) or
    (v_previous_status = 'under_review' and v_next_status in ('approved', 'rejected', 'cancelled')) or
    (v_previous_status = 'approved' and v_next_status in ('processing', 'completed', 'failed', 'cancelled')) or
    (v_previous_status = 'processing' and v_next_status in ('completed', 'failed'))
  );

  if not v_transition_allowed then
    raise exception 'Invalid withdrawal status transition: % -> %', v_previous_status, v_next_status;
  end if;

  if v_next_status in ('rejected', 'failed', 'cancelled') and v_request.release_ledger_ref is null then
    v_release_ref := v_request.withdrawal_id || ':release';
    v_release_ledger_ref := 'LED-WDR-' || v_request.withdrawal_id || '-RELEASE';

    insert into public.finance_ledger (
      ledger_ref,
      reference_type,
      reference_id,
      related_withdrawal_id,
      transaction_type,
      entry_type,
      user_id,
      account_id,
      amount,
      direction,
      status,
      currency,
      memo,
      created_at
    )
    values (
      v_release_ledger_ref,
      'withdrawal',
      v_release_ref,
      v_request.withdrawal_id,
      'withdrawal_release',
      'withdrawal_release',
      v_request.user_id,
      v_request.account_id,
      abs(v_request.request_amount),
      'credit',
      'reversed',
      v_request.currency,
      coalesce(nullif(p_reason, ''), 'Withdrawal reserve released'),
      now()
    )
    on conflict (reference_type, reference_id) do nothing;

    get diagnostics v_affected_rows = row_count;
    if v_affected_rows = 0 then
      perform public.finhalo_assert_withdrawal_ledger_entry(
        v_release_ref,
        v_request.withdrawal_id,
        v_request.user_id,
        v_request.account_id,
        'withdrawal_release',
        'credit',
        'reversed',
        abs(v_request.request_amount),
        v_request.currency
      );
    end if;

    v_request.release_ledger_ref := v_release_ledger_ref;
  end if;

  if v_next_status = 'completed' and v_request.payout_ledger_ref is null then
    v_payout_ref := v_request.withdrawal_id || ':payout';
    v_payout_ledger_ref := 'LED-WDR-' || v_request.withdrawal_id || '-PAYOUT';

    insert into public.finance_ledger (
      ledger_ref,
      reference_type,
      reference_id,
      related_withdrawal_id,
      transaction_type,
      entry_type,
      user_id,
      account_id,
      amount,
      direction,
      status,
      currency,
      memo,
      created_at
    )
    values (
      v_payout_ledger_ref,
      'withdrawal',
      v_payout_ref,
      v_request.withdrawal_id,
      'withdrawal_payout',
      'withdrawal_payout',
      v_request.user_id,
      v_request.account_id,
      abs(v_request.request_amount),
      'debit',
      'posted',
      v_request.currency,
      'Withdrawal completed, net payout ' || coalesce(v_request.net_amount::text, '0'),
      now()
    )
    on conflict (reference_type, reference_id) do nothing;

    get diagnostics v_affected_rows = row_count;
    if v_affected_rows = 0 then
      perform public.finhalo_assert_withdrawal_ledger_entry(
        v_payout_ref,
        v_request.withdrawal_id,
        v_request.user_id,
        v_request.account_id,
        'withdrawal_payout',
        'debit',
        'posted',
        abs(v_request.request_amount),
        v_request.currency
      );
    end if;

    v_request.payout_ledger_ref := v_payout_ledger_ref;
  end if;

  update public.withdrawal_requests as wr
  set
    status = v_next_status,
    reviewed_at = case
      when v_next_status in ('under_review', 'approved', 'rejected', 'cancelled')
      then coalesce(wr.reviewed_at, now())
      else wr.reviewed_at
    end,
    reviewed_by = case
      when v_next_status in ('under_review', 'approved', 'rejected', 'cancelled')
      then coalesce(nullif(btrim(coalesce(p_actor, '')), ''), wr.reviewed_by)
      else wr.reviewed_by
    end,
    processed_at = case
      when v_next_status in ('processing', 'completed', 'failed')
      then coalesce(wr.processed_at, now())
      else wr.processed_at
    end,
    processed_by = case
      when v_next_status in ('processing', 'completed', 'failed')
      then coalesce(nullif(btrim(coalesce(p_actor, '')), ''), wr.processed_by)
      else wr.processed_by
    end,
    rejection_reason = case
      when v_next_status in ('rejected', 'failed', 'cancelled')
      then coalesce(nullif(btrim(coalesce(p_reason, '')), ''), wr.rejection_reason)
      else wr.rejection_reason
    end,
    review_notes = case
      when nullif(btrim(coalesce(p_notes, '')), '') is not null
      then coalesce(wr.review_notes || E'\n', '') || btrim(p_notes)
      else wr.review_notes
    end,
    release_ledger_ref = coalesce(v_request.release_ledger_ref, wr.release_ledger_ref),
    payout_ledger_ref = coalesce(v_request.payout_ledger_ref, wr.payout_ledger_ref),
    updated_at = now()
  where wr.withdrawal_id = v_request.withdrawal_id;

  insert into public.withdrawal_request_events (
    withdrawal_id,
    previous_status,
    next_status,
    actor,
    reason,
    notes,
    metadata,
    created_at
  )
  values (
    v_request.withdrawal_id,
    v_previous_status,
    v_next_status,
    nullif(btrim(coalesce(p_actor, '')), ''),
    nullif(btrim(coalesce(p_reason, '')), ''),
    nullif(btrim(coalesce(p_notes, '')), ''),
    jsonb_build_object(
      'reserve_ledger_ref', v_request.reserve_ledger_ref,
      'release_ledger_ref', v_request.release_ledger_ref,
      'payout_ledger_ref', v_request.payout_ledger_ref
    ),
    now()
  );

  return query
  select
    wr.withdrawal_id,
    v_previous_status,
    wr.status,
    wr.reserve_ledger_ref,
    wr.release_ledger_ref,
    wr.payout_ledger_ref
  from public.withdrawal_requests as wr
  where wr.withdrawal_id = v_request.withdrawal_id;
end;
$$;
